# See https://ktor.io/docs/server-configuration-file.html#config-basic and
# https://ktor.io/docs/server-configuration-file.html#predefined-properties

# NOT IN USE CURRENTLY, READ README

#ktor:
#  application:
#    modules:
#      - no.ruter.trafikk.ApplicationKt.module
#  deployment:
#    port: 8080

