# See https://ktor.io/docs/server-configuration-file.html#config-basic and
# https://ktor.io/docs/server-configuration-file.html#predefined-properties

### KTOR ###
ktor:
  # Deployment
  deployment:
    port: 8079
    host: 0.0.0.0
