# See https://ktor.io/docs/server-configuration-file.html#config-basic and
# https://ktor.io/docs/server-configuration-file.html#predefined-properties

# NOT IN USE CURRENTLY, READ README

#ktor:
#  application:
#    modules:
#      - trafikk.ruter.no.ApplicationKt.module
#  deployment:
#    port: 8080

